### ISSUE TITLE
No "git" module found for foxify

### ISSUE THREAD

**Issue by pyrox0** [M4cs/foxify-cli#3]
**Describe the bug**
ModuleNotFoundError when running foxify.

### Before creating your bug report, have you checked the [Troubleshooting](https://github.com/M4cs/foxify-cli/wiki/Troubleshooting) guide? Yes.

**To Reproduce**
Install foxify, then run 
`foxify`
you will get 
`ModuleNotFoundError: No module named 'git'`

**Expected behavior**
I expected foxify to work.

**Environment**
 - OS: macOS
 - Python Version 3.7.7, from brew.

**Additional context**
I tried installing `foxify` from pip, and that didn't work. Then I `git-py` from pip to try and be able to `import git`, but that didn't help. Then I removed the pip version and installed manually with `git clone`, etc. neither worked.

**Comment by oscarmcm** [comment]
Hi @ModdedGamers 

This is means that you don't have gitpython module installed.

You can install it by doing:

```
$ pip install gitpython
```

probably, it's a good idea to add this as a direct dependency to **foxify-cli**.

**Comment by pyrox0** [comment]
Thanks!

**Comment by M4cs** [comment]
Going to be pushing an update shortly that fixes this.
